require('./style.scss')
require('./header.scss')
require('./cards.scss')
require('./adaptive.scss')
require('./assets/fonts/LeksaSans.eot')
require('./assets/fonts/LeksaSans.eot?#iefix')
require('./assets/fonts/LeksaSans.woff2')
require('./assets/fonts/LeksaSans.woff')
require('./assets/fonts/LeksaSans.ttf')
require('./assets/img/$.svg')
require('./assets/img/background.png')
require('./assets/img/card.svg')
require('./assets/img/coins.png')
require('./assets/img/coins1.png')
require('./assets/img/coins2.png')
require('./assets/img/coins3.png')
require('./assets/img/coins4.png')
require('./assets/img/coins5.png')
require('./assets/img/coins6.png')
require('./assets/img/crystal.png')
require('./assets/img/crystal1.png')
require('./assets/img/crystal2.png')
require('./assets/img/crystal3.png')
require('./assets/img/crystal4.png')
require('./assets/img/crystal5.png')
require('./assets/img/crystal6.png')
require('./assets/img/header-button__back.svg')
require('./assets/img/header-background.png')
require('./assets/img/header-button__home.svg')
require('./assets/img/plus.svg')



